config/routes.rb
Shrent::Application.routes.draw do
  get "admin/sessions/new"

  get "admin/users/new"
  get "logout" => "admin/sessions#destroy", :as => "logout"  
  get "login" => "admin/sessions#new", :as => "login"  
  get "signup" => "admin/users#new", :as => "signup"  
  resources :houses , :only => [:index,:show]
  namespace :admin do 
    resources :users  
    resources :sessions
    resources :messages
    resources :houses
  end  
  root :to => "welcome#index"  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shrent</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="container">  


    <div class="navbar navbar-fixed-top">
     <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="#">上海租房后台管理</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "微信消息",admin_messages_path%></li>
            <li><%= link_to "租房信息",admin_houses_path%></li>
          </ul>
          <ul class="nav pull-right">
            <% if current_user %>  
            <li> <%= link_to current_user.username %>  </li>
               <li> <%= link_to "注销", logout_path %>  </li>
              <% else %>  
              <li><%= link_to "注册", signup_path %> </li>
               <li>  <%= link_to "登录", login_path  %>.  </li>
                <% end %>  
              </ul>
            </div>
          </div>
        </div>
      </div>
      <% flash.each do |name, msg| %>  
      <%= content_tag :div, msg, :id => "flash_#{name}" %>  
      <% end %>  
      <%= yield %>  
    </div>  
  </body>
  </html>

app/views/layouts/weixin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || "上海租房"%></title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <%= stylesheet_link_tag    "weixin", :media => "all" %>
  <%#= javascript_include_tag "application" %>
  <%#= csrf_meta_tags %>
</head>
<body>
	 <div id="container">  
		<%= yield %> 
	 </div>
</body>
</html>